name: Output Information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context
              run: echo "The workflow name is ${{ github.workflow }} and the event that triggered it is ${{ github.event_name }} ${{toJson(github)}}"